#!/usr/bin/env bash

set -Eeuo pipefail

readonly SPINNER_FRAMES=(
  '|'
  '/'
  '-'
  '\\'
)

spinner_active=0
loaded_env_files=()

cleanup() {
  if ((spinner_active)); then
    printf '\n'
  fi
}

fail() {
  printf 'Error: %s\n' "$1" >&2
  exit 1
}

log_step() {
  printf '\n==> %s\n' "$1"
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing required command: $1"
}

render_env_file() {
  bun --eval '
const { randomBytes } = require("node:crypto");

const source = await Bun.file("idp-client.yaml").text();
const config = Bun.YAML.parse(source);
const values = config.runtime_env?.values ?? {};
const generated = config.runtime_env?.generated ?? {};
const env = {};

function getPath(path) {
  return path.split(".").reduce((value, key) => value?.[key], config);
}

function resolveValue(value) {
  if (["string", "number", "boolean"].includes(typeof value)) {
    return String(value);
  }

  if (!value || typeof value !== "object") {
    throw new Error("Unsupported runtime_env value.");
  }

  if (value.from) {
    const resolved = getPath(value.from);

    if (Array.isArray(resolved)) {
      return resolved.join(value.join ?? " ");
    }

    if (resolved === undefined || resolved === null) {
      throw new Error(`Missing idp-client.yaml path: ${value.from}`);
    }

    return String(resolved);
  }

  if (value.template) {
    return String(value.template).replace(/\$\{([A-Z0-9_]+)\}/g, (_match, key) => {
      if (env[key] === undefined) {
        throw new Error(`Missing template value: ${key}`);
      }

      return env[key];
    });
  }

  throw new Error("Unsupported runtime_env object value.");
}

for (const [key, spec] of Object.entries(generated)) {
  if (spec?.type === "hex") {
    env[key] = randomBytes(Number(spec.bytes)).toString("hex");
  } else {
    env[key] = "";
  }
}

for (const [key, value] of Object.entries(values)) {
  if (!(value && typeof value === "object" && value.template)) {
    env[key] = resolveValue(value);
  }
}

for (const [key, value] of Object.entries(values)) {
  if (value && typeof value === "object" && value.template) {
    env[key] = resolveValue(value);
  }
}

function quote(value) {
  return `"${String(value)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, "\\\"")
    .replace(/\$/g, "\\$")
    .replace(/`/g, "\\`")}"`;
}

function commentsFor(key) {
  const spec = generated[key];

  if (key === "AUTH_HYDRA_SECRET") {
    return [
      "# Fill after registering the hydra_client from idp-client.yaml in Hydra.",
      "# The platform orchestrator can generate this automatically.",
    ];
  }

  if (spec?.type === "manual") {
    return ["# Fill with the first local admin password before rerunning ./init.sh."];
  }

  return [];
}

const preferredOrder = [
  "DATABASE_HOST",
  "DATABASE_PORT",
  "DATABASE_USER",
  "DATABASE_PASSWORD",
  "DATABASE_NAME",
  "DATABASE_URL",
  "PORT",
  "AUTH_URL",
  "AUTH_SECRET",
  "HYDRA_ADMIN_URL",
  "AUTH_HYDRA_ID",
  "AUTH_HYDRA_SECRET",
  "AUTH_HYDRA_ISSUER",
  "AUTH_HYDRA_AUDIENCE",
  "AUTH_HYDRA_SCOPE",
  "ADMIN_EMAIL",
  "ADMIN_PASSWORD",
  "ADMIN_NAME",
  "DEV_BYPASS_AUTH",
];

const keys = [
  ...preferredOrder.filter((key) => key in env),
  ...Object.keys(env)
    .filter((key) => !preferredOrder.includes(key))
    .sort(),
];

const lines = [
  "# Generated by ./init.sh from idp-client.yaml.",
  "# This file is ignored by Git. Keep local credentials here only.",
  "",
];

for (const key of keys) {
  lines.push(...commentsFor(key));
  lines.push(`${key}=${quote(env[key])}`);
}

process.stdout.write(`${lines.join("\n")}\n`);
'
}

create_env_file_from_contract() {
  local env_file=".env.local"
  local tmp_file="${env_file}.tmp"

  [[ -f idp-client.yaml ]] || fail 'Missing idp-client.yaml. Cannot generate .env.local.'

  render_env_file >"${tmp_file}"
  chmod 600 "${tmp_file}"
  mv "${tmp_file}" "${env_file}"

  printf 'Created %s from idp-client.yaml.\n' "${env_file}"
  printf 'Fill AUTH_HYDRA_SECRET, then rerun ./init.sh.\n'
}

require_env_var() {
  local name="$1"
  local value="${!name:-}"

  [[ -n "${value//[[:space:]]/}" ]] || fail "Missing required env variable: ${name}. Fill .env.local before rerunning this script."
}

require_env_vars() {
  local name
  local required=(
    DATABASE_HOST
    DATABASE_PORT
    DATABASE_USER
    DATABASE_PASSWORD
    DATABASE_NAME
    DATABASE_URL
    PORT
    AUTH_URL
    AUTH_SECRET
    HYDRA_ADMIN_URL
    AUTH_HYDRA_ID
    AUTH_HYDRA_SECRET
    AUTH_HYDRA_ISSUER
    AUTH_HYDRA_AUDIENCE
    AUTH_HYDRA_SCOPE
    ADMIN_EMAIL
    ADMIN_PASSWORD
  )

  for name in "${required[@]}"; do
    require_env_var "${name}"
  done
}

load_env_files() {
  local found=0
  local env_file

  for env_file in ../.env .env .env.local; do
    if [[ -f "$env_file" ]]; then
      loaded_env_files+=("$env_file")
      set -a
      # shellcheck disable=SC1090
      source "$env_file"
      set +a
      found=1
    fi
  done

  if ! ((found)); then
    create_env_file_from_contract
    exit 1
  fi
}

format_env_files() {
  local IFS=', '
  printf '%s' "${loaded_env_files[*]}"
}

install_dependencies() {
  bun install
}

wait_for_postgres() {
  local timeout_seconds="${1:-60}"
  local message="${2:-Waiting for PostgreSQL to accept connections}"
  local start_time=$SECONDS
  local frame_index=0

  spinner_active=1

  while true; do
    if docker compose exec -T postgres sh -c \
      'pg_isready -h 127.0.0.1 -U "$POSTGRES_USER" -d "$POSTGRES_DB"' \
      >/dev/null 2>&1; then
      spinner_active=0
      printf '\r%s done.\033[K\n' "$message"
      return 0
    fi

    if ((SECONDS - start_time >= timeout_seconds)); then
      spinner_active=0
      printf '\r%s timed out after %ss.\033[K\n' "$message" "$timeout_seconds" >&2
      return 1
    fi

    printf '\r%s %s' \
      "$message" \
      "${SPINNER_FRAMES[frame_index % ${#SPINNER_FRAMES[@]}]}"
    sleep 0.1
    ((frame_index += 1))
  done
}

main() {
  trap cleanup EXIT INT TERM

  require_command bun
  load_env_files
  require_env_vars

  require_command docker
  require_command curl

  log_step "Using env files: $(format_env_files)"

  docker compose version >/dev/null 2>&1 || fail 'Docker Compose plugin is required.'
  docker compose config >/dev/null

  export PORT="${PORT:-3001}"

  if ! curl -fsS "${HYDRA_ADMIN_URL}/health/ready" >/dev/null 2>&1; then
    fail 'Hydra admin API is unreachable. Start auth-server first and verify HYDRA_ADMIN_URL.'
  fi

  log_step 'Resetting Docker services'
  docker compose down -v --remove-orphans

  log_step 'Installing dependencies'
  install_dependencies

  log_step 'Starting Docker services'
  docker compose up -d

  printf '\n'
  wait_for_postgres 60 'Waiting for PostgreSQL to accept connections'

  log_step 'Running database migrations'
  bun run db:migrate:deploy

  log_step 'Seeding database'
  bun run db:seed

  log_step 'Starting development server'
  printf 'Auth admin panel will run on http://localhost:%s\n' "$PORT"
  exec bun run dev
}

main "$@"
